# Microservices registration url
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka

# For correct working api gateway
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# Roots config
      # Account-service route settings
      routes[0]:
        id: account-service
        uri: lb://accounts
        predicates[0]: Path=/main/test
        predicates[1]: Method=GET
      # Bill-service route settings
      routes[1]:
        id: bill-service
        uri: lb://bills
        predicates[0]: Path=/main/test
        predicates[1]: Method=GET
      # Deposit-service route settings
      routes[2]:
        id: deposit-service
        uri: lb://deposit
        predicates[0]: Path=/main/test
        predicates[1]: Method=GET
      # Payment-service route settings
      routes[3]:
        id: payment-service
        uri: lb://payment
        predicates[0]: Path=/main/test
        predicates[1]: Method=GET
